In [3]:
import numpy as np

import cmath

def solve_quadratic(a, b, c):
    """
    Solves the quadratic equation ax^2 + bx + c = 0.
    
    Parameters:
    a (float): Coefficient of x^2
    b (float): Coefficient of x
    c (float): Constant term
    
    Returns:
    tuple: A tuple containing the two solutions, which can be real or complex numbers.
    """
    # Calculate the discriminant
    discriminant = b**2 - 4*a*c
    
    # Calculate the two solutions
    root1 = (-b + cmath.sqrt(discriminant)) / (2*a)
    root2 = (-b - cmath.sqrt(discriminant)) / (2*a)
    
    return (root1, root2)

# Example usage
a = 1
b = -3
c = 2

roots = solve_quadratic(a, b, c)
print(f"The roots of the equation are: {roots[0]} and {roots[1]}")

The roots of the equation are: (2+0j) and (1+0j)


In [4]:
import numpy as np

def solve_3x3_equation(coefficients, constants):
    """
    Solves a system of linear equations with 3 variables.
    
    Arguments:
    coefficients -- a 3x3 list or numpy array representing the coefficients of the equations
    constants -- a list or numpy array of length 3 representing the constants
    
    Returns:
    A numpy array containing the values of x, y, z
    """
    A = np.array(coefficients)
    b = np.array(constants)
    
    # Check if the matrix A is invertible
    if np.linalg.det(A) == 0:
        raise ValueError("The coefficient matrix is singular and cannot be inverted.")
    
    # Solve for x, y, z
    solution = np.linalg.solve(A, b)
    
    return solution

# Example usage:
coefficients = [
    [2, -1, 3],
    [1,  0, 1],
    [4,  1, 2]
]
constants = [5, 3, 8]

solution = solve_3x3_equation(coefficients, constants)
print("Solution:", solution)

Solution: [-2.  6.  5.]


In [5]:
import numpy as np

def solve_2x2_equation(coefficients, constants):
    """
    Solves a system of linear equations with 3 variables.
    
    Arguments:
    coefficients -- a 3x3 list or numpy array representing the coefficients of the equations
    constants -- a list or numpy array of length 3 representing the constants
    
    Returns:
    A numpy array containing the values of x, y, z
    """
    A = np.array(coefficients)
    b = np.array(constants)
    
    # Check if the matrix A is invertible
    if np.linalg.det(A) == 0:
        raise ValueError("The coefficient matrix is singular and cannot be inverted.")
    
    # Solve for x, y, z
    solution = np.linalg.solve(A, b)
    
    return solution

# Example usage:
coefficients = [
    [2, -1],
    [1,  0],

]
constants = [5, 3]

solution = solve_2x2_equation(coefficients, constants)
print("Solution:", solution)

Solution: [3. 1.]


In [14]:
pa = 100/(1.03)**2
pb = 100/(1.03)**10

da = 1
db = 5
p = 98.1414507985948
dp = 1.92723570430286

coefficients = [
    [pa, pb],
    [pa*da,  pb*db],

]
constants = [p, dp*p]

na, nb = solve_2x2_equation(coefficients, constants)
print("Solution:", solution)

Solution: [0.79982722 0.30574184]


In [18]:
ca = ((1)*(1.5))/(1.03)**2
cb = ((5)*(5.5))/(1.03)**2

print(ca, cb)

1.4138938637006315 25.921387501178245


In [16]:
(na*ca*pa + nb*cb*pb )/p

7.094949644611735

In [70]:
rate_tree = np.array([[0.055, 0.071, 0.087],
             [0, 0.042, 0.0575],
             [0, 0, 0.031]])
rate_tree

array([[0.055 , 0.071 , 0.087 ],
       [0.    , 0.042 , 0.0575],
       [0.    , 0.    , 0.031 ]])

In [71]:
bp = np.zeros((4,4))
bp[:, 3] = 1

for i in range(2, -1, -1):
    for j in range(i+1):
        bp[j, i] = 0.5*(bp[j, i+1] + bp[j+1, i+1])/(1+rate_tree[j, i])
bp

array([[0.84840326, 0.8709569 , 0.9199632 , 1.        ],
       [0.        , 0.91917398, 0.94562648, 1.        ],
       [0.        , 0.        , 0.9699321 , 1.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [73]:
bp = np.zeros((3,3))
bp[:, 2] = 1

for i in range(1, -1, -1):
    for j in range(i+1):
        bp[j, i] = 0.5*(bp[j, i+1] + bp[j+1, i+1])/(1+rate_tree[j, i])

bp

array([[0.89734584, 0.93370682, 1.        ],
       [0.        , 0.9596929 , 1.        ],
       [0.        , 0.        , 1.        ]])

In [79]:
i = (93.27948 - 95.77793)/0.029



In [63]:

c = 200*0.12
payoff = np.ones((4,4))*c
for i in range(4):
    for j in range(4):
        if i>j:
            payoff[i,j]=0
payoff[0,0]=0
payoff[:,3] +=200
payoff

array([[  0.,  24.,  24., 224.],
       [  0.,  24.,  24., 224.],
       [  0.,   0.,  24., 224.],
       [  0.,   0.,   0., 224.]])

In [64]:
pv = np.zeros((4,4))

for i in range(2, -1, -1):
    for j in range(i+1):
        pv[j, i] = 0.5*(pv[j, i+1] +payoff[j, i+1] + payoff[j+1, i+1] + pv[j+1, i+1])/(1+rate_tree[j, i])

In [65]:
pv

array([[234.32744599, 217.5033091 , 206.07175713,   0.        ],
       [  0.        , 228.92760194, 211.82033097,   0.        ],
       [  0.        ,   0.        , 217.26479146,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ]])

In [80]:
d = (pv[0,1]- pv[1,1])/(rate_tree[0,1]-rate_tree[1,1])

In [81]:
d/i

4.572552115299265

In [67]:
(217.5033 - 228.9276)/(0.029)

-393.9413793103454

In [72]:
bp = np.zeros((3,3))
bp[:, 2] = 1

for i in range(1, -1, -1):
    for j in range(i+1):
        bp[j, i] = 0.5*(bp[j, i+1] + bp[j+1, i+1])/(1+rate_tree[j, i])

bp

array([[0.89734584, 0.93370682, 1.        ],
       [0.        , 0.9596929 , 1.        ],
       [0.        , 0.        , 1.        ]])

In [37]:
bp

array([[0.89734584, 0.93370682, 1.        ],
       [0.        , 0.9596929 , 1.        ],
       [0.        , 0.        , 1.        ]])

In [39]:
0.84840326/0.89734584

0.945458509062682

In [44]:
bp = np.zeros((4,4))
bp[:, 3] = 1

for i in range(2, -1, -1):
    for j in range(i+1):
        bp[j, i] = 0.5*(bp[j, i+1] + bp[j+1, i+1])/(1+rate_tree[j, i])


bp

array([[0.84840326, 0.8709569 , 0.9199632 , 1.        ],
       [0.        , 0.91917398, 0.94562648, 1.        ],
       [0.        , 0.        , 0.9699321 , 1.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [45]:
for i in range(1, -1, -1):
    for j in range(i+1):
        bp[j, i] = 0.5*(bp[j, i+1] + bp[j+1, i+1])


bp

array([[0.94528707, 0.93279484, 0.9199632 , 1.        ],
       [0.        , 0.95777929, 0.94562648, 1.        ],
       [0.        , 0.        , 0.9699321 , 1.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [68]:
(0.93279484 - 0.95777929)/0.029

-0.8615327586206875